import { z } from "zod";

export const ollama_models = [
  // cloud options
  "glm-4.6",
  "kimi-k2:1t",
  "kimi-k2-thinking",
  "qwen3-coder:480b",
  "deepseek-v3.1:671b",
  "gpt-oss:120b",
  "gpt-oss:20b",
  "qwen3-vl:235b-instruct",
  "qwen3-vl:235b",
  "minimax-m2",
  "mistral-large-3:675b-cloud",

  // other modules
  "llama2",
  "llama2:7b",
  "llama2:13b",
  "llama2:70b",
  "llama3",
  "llama3:8b",
  "llama3:70b",
  "llama3:70b-instruct",
  "llama3:8b-instruct",
  "llama3.1",
  "llama3.1:8b",
  "llama3.1:70b",
  "llama3.2",
  "llama3.3",
  "magistral",
  "devstral",
  "mistral",
  "mistral:7b",
  "mistral-small3.1",
  "mistral-small3.2",
  "mistral:instruct",
  "mistral:latest",

  "ministral-3:3b",
  "ministral-3:8b",
  "ministral-3:14b",
  "ministral-3:3b-cloud",
  "ministral-3:8b-cloud",
  "ministral-3:14b-cloud",
  "mixtral",
  "mixtral:8x7b",
  "mixtral:8x22b",
  "phi",
  "phi2",
  "phi3",
  "phi3:mini",
  "phi3:medium",
  "qwen",
  "qwen2",
  "qwen2:7b",
  "qwen2:72b",
  "gemma",
  "gemma2",
  "gemma2:9b",
  "gemma2:27b",
  "gemma2:2b",
  "qwen2.5vl:3b",
  "qwen2.5-coder:0.5b",
  "qwen2.5-coder:1.5b",
  "qwen2.5-coder:3b",
  "qwen2.5-coder:7b",
  "qwen2.5-coder:14b",
  "qwen2.5-coder:32b",

  "qwen2.5vl-coder:b",

  "qwen3-coder:30b",
  "qwen3-coder:480",
  "qwen3-coder:480-cloud",

  "qwen3:0.6b",
  "qwen3:1.7b",
  "qwen3:4b",
  "qwen3:8b",
  "qwen3:16b",
  "qwen3:30b",
  "qwen3:32b",
  "qwen3:235b",

  // Code Models
  "codellama",
  "codellama:7b",
  "codellama:13b",
  "codellama:34b",
  "starcoder",
  "starcoder2",
  "deepseek-coder",
  "deepseek-chat",
  "wizardcoder",
  "wizard-vicuna",
  "wizardlm",
  "wizardlm:13b",

  // Vision Models
  "llava",
  "llava:7b",
  "llava:13b",
  "llava:34b",
  "llava-llama3",
  "moondream",
  "bakllava",
  "minicpm-v",
  "minicpm-v2.6",
  "cogvlm",
  "qwen-vl",
  "vilar",

  // Specialized Models
  "vicuna",
  "vicuna:7b",
  "vicuna:13b",
  "vicuna:7b-1.1",
  "alpaca",
  "dolphin-mistral",
  "dolphin-mistral:7b",
  "neural-chat",
  "neural-chat:7b",
  "starling-lm",
  "starling-lm:7b",
  "solar",
  "solar:10.7b",
  "samantha-mistral",
  "samantha-mistral:7b",
  "nous-hermes",
  "nous-hermes2",
  "nous-hermes2:13b",
  "orca-mini",
  "orca-mini:3b",
  "orca-mini:7b",
  "stable-beluga",
  "stable-beluga:7b",
  "stable-beluga:13b",
  "ultralytics/ultralytics",

  "gemma3",

  // Small/Efficient Models
  "tinyllama",
  "tinyllama:1.1b",
  "minicpm-1.2b",

  // Medical/Scientific
  "meditron",
  "meditron:7b",
  "meditron:70b",
] as const;
